hilo_project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hilo.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hilo_project/hilo/urls.py
from django.urls import path
from . import views

app_name = 'hilo'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

hilo_project/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
]

hilo_project/hilo/models.py
from django.db import models

# Create your models here.

hilo_project/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField('upload/users/profile/', null=True, blank=True)
    phone = models.CharField(max_length=13, null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Foydalanuvchi'
        verbose_name_plural = 'Foydalanuvchilar'

    def get_image(self):
        if self.image:
            return self.image.url
        return "https://png.pngitem.com/pimgs/s/111-1114675_user-login-person-man-enter-person-login-icon.png"

hilo_project/user/forms.py
from django import forms

from user.models import User


class RegisterForm(forms.ModelForm):
    username = forms.CharField(
        label='Username', max_length=30, required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
                'class': 'form-control',
                'id': 'username'
            }
        )
    )
    email = forms.EmailField(
        label='Email', required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Emial',
                'class': 'form-control',
                'id': 'email'
            }
        )
    )
    password1 = forms.CharField(
        label='Make password', required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'class': 'form-control',
                'id': 'password1'
            }
        )
    )
    password2 = forms.CharField(
        label='Make password', required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'class': 'form-control',
                'id': 'password1'
            }
        )
    )
    phone = forms.CharField(label='Phone number', max_length=15, required=False)
    address = forms.CharField(label='Address', max_length=150, required=False)
    image = forms.ImageField(label='Profile picture', required=False)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords must match')
        return password2

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email address already exists')
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username already exists')
        if len(username) > 5:
            raise forms.ValidationError('Username must be less than 6 characters')
        return username

    def create_user(self):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.save()
        return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'phone', 'address', 'image')


class LoginForm(forms.ModelForm):
    username = forms.CharField(
        label='Username', max_length=30, required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
                'class': 'form-control',
                'id': 'username'
            }
        )
    )
    password = forms.CharField(
        label='Password', required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'class': 'form-control',
                'id': 'password1'
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'password')

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username does not exist')
        user = User.objects.get(username=username)
        if not user.check_password(password):
            raise forms.ValidationError('Incorrect password')
        self.cleaned_data['user'] = self.get_user()
        return self.cleaned_data

    def get_user(self):
        username = self.cleaned_data.get('username')
        return User.objects.get(username=username)

hilo_project/hilo/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import View


class HomeView(View):
    def get(self, request):
        context = {
            'title': 'Bosh sahifa',
        }
        return render(request, 'hilo/index.html', context)

hilo_project/user/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib import messages

from .forms import RegisterForm, LoginForm


class Register(View):
    def get(self, request):
        context = {
            'form': RegisterForm(),
            'title': "Ro'yxatdan o'tish",
            'page_name': "Register",
            'page_icon': "https://static.vecteezy.com/system/resources/thumbnails/010/695/423/small_2x/fill-out-the-e-mail-form-with-a-pen-vector.jpg"
        }
        return render(request, 'user/register.html', context)

    def post(self, request):
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.create_user()
            messages.success(request, "Ro'yxatdan o'tdingiz! Tizimga kirish uchun login qilishni unutmaslik qoldi.")
            return redirect('user:login')
        context = {
            'form': form,
            'title': "Ro'yxatdan o'tish",
            'page_name': "Register",
            'page_icon': "https://static.vecteezy.com/system/resources/thumbnails/010/695/423/small_2x/fill-out-the-e-mail-form-with-a-pen-vector.jpg"
        }
        return render(request, 'user/register.html', context)


class Login(View):
    def get(self, request):
        context = {
            'form': LoginForm(),
            'title': 'Kirish',
            'page_name': 'Login',
            'page_icon': 'https://www.freeiconspng.com/thumbs/login-icon/door-login-icon--1.png'
        }
        return render(request, 'user/login.html', context)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            login(request, user)
            messages.success(request, f"Salom {user.username} siz tizimga kirdingiz!")
            return redirect('hilo:home')
        else:
            context = {
                'form': form,
                'title': 'Kirish',
                'page_name': 'Login',
                'page_icon': 'https://www.freeiconspng.com/thumbs/login-icon/door-login-icon--1.png'
            }
            return render(request, 'user/login.html', context)


def logout_user(request):
    logout(request)
    messages.warning(request, 'Siz tizimdan chiqdingiz!')
    return redirect('user:login')

hilo_project/hilo/templates/hilo/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- New Arrival Area -->
    {% include 'components/arrival.html' %}
    <!-- New Arrival Area End -->

    <!-- Choose Area -->
    {% include 'components/choose.html' %}
    <!-- Choose Area End -->

    <!-- Trending Area -->
    {% include 'components/trending.html' %}
    <!-- Trending Area End -->

    <!-- Brand Area -->
    {% include 'components/brand.html' %}
    <!-- Brand Area End -->

    <!-- Testimonials Area -->
    {% include 'components/testimonials.html' %}
    <!-- Testimonials Area End -->

    <!-- Offer Area End -->
    {% include 'components/offer.html' %}
    <!-- Offer Area End -->

    <!-- Blog Area -->
    {% include 'components/blog.html' %}
    <!-- Blog Area End -->

    <!-- Newsletter Area Section -->
    {% include 'components/newsletter.html' %}
    <!-- Newsletter Area Section End -->
{% endblock %}

hilo_project/templates/_components/banner.html
{% load static %}


<div class="banner-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="banner-item-content">
                    <span>WELCOME TO OUR SHOP</span>
                    <h1>Order the Organic Foods Now!</h1>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscins elitr, seddiams nonumy eirmod.</p>
                    <a href="#" class="default-btn btn-bg-one">Order Now</a>
                    <img src="{% static 'images/home-one/home-one-img1.png' %}" alt="Banner Images">
                </div>
            </div>

            <div class="col-lg-4">
                <div class="row">
                    <div class="col-lg-12 col-md-6">
                        <div class="banner-item-side">
                            <h3>Sign Up on Shop</h3>
                            <span>Get a 30% Offer!</span>
                            <a href="#" class="newslette-btn">Newsletter</a>
                            <img src="{% static 'images/home-one/home-one-img2.png' %}" alt="Banner Images">
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-6">
                        <div class="banner-item-side-2">
                            <h3>Big Sale Offer</h3>
                            <span>Up to 70% Discount</span>
                            <a href="shop-grid.html" class="shop-btn">Shop Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

hilo_project/templates/_components/footer.html
{% load static %}

<footer class="footer-area">
    <div class="container">
        <div class="footer-top pt-100 pb-70">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <div class="footer-logo">
                            <a href="index.html">
                                <img src="{% static 'images/logos/footer-logo.png' %}" class="footer-logo1"
                                     alt="Images">
                                <img src="{% static 'images/logos/logo-1.png' %}" class="footer-logo2" alt="Images">
                            </a>
                        </div>
                        <p>
                            We are one of the best & quality full in market. Let's join.
                        </p>
                        <ul class="footer-list-contact">
                            <li>
                                <i class='bx bx-home'></i>
                                <a href="#">Virgil A Stanton, Virginia, USA</a>
                            </li>
                            <li>
                                <i class='bx bx-phone-call'></i>
                                <a href="tel:+1(123)-456-7890">+1 (123) 456 7890</a>
                            </li>
                            <li>
                                <i class='bx bx-envelope'></i>
                                <a href="mailto:hello@hilo.com">hello@hilo.com</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h3>Services</h3>
                        <ul class="footer-list">
                            <li>
                                <a href="wordpress-hosting.html" target="_blank">
                                    My Account
                                </a>
                            </li>
                            <li>
                                <a href="tracking-order.html" target="_blank">
                                    Tracking Order
                                </a>
                            </li>
                            <li>
                                <a href="customer-services.html" target="_blank">
                                    Customer Services
                                </a>
                            </li>
                            <li>
                                <a href="compare.html" target="_blank">
                                    Compare
                                </a>
                            </li>
                            <li>
                                <a href="wishlist.html" target="_blank">
                                    Wishlist
                                </a>
                            </li>
                            <li>
                                <a href="privacy-policy.html" target="_blank">
                                    Privacy Policy
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h3>Information</h3>
                        <ul class="footer-list">
                            <li>
                                <a href="index.html" target="_blank">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="about.html" target="_blank">
                                    About Us
                                </a>
                            </li>
                            <li>
                                <a href="blog-details.html" target="_blank">
                                    Blog Details
                                </a>
                            </li>
                            <li>
                                <a href="shop-details.html" target="_blank">
                                    Shop Details
                                </a>
                            </li>
                            <li>
                                <a href="testimonials.html" target="_blank">
                                    Testimonials
                                </a>
                            </li>
                            <li>
                                <a href="team.html" target="_blank">
                                    Team
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h3>Follow Us</h3>
                        <p>We are one of the best & quality full in market. Let's join.</p>
                        <form class="footer-form-area">
                            <input type="email" class="form-control" placeholder="Email">
                            <button class="subscribe-btn" type="submit">
                                <i class='bx bx-paper-plane'></i>
                            </button>
                        </form>

                        <ul class="social-link">
                            <li>
                                <a href="#" target="_blank"><i class='bx bxl-facebook'></i></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><i class='bx bxl-twitter'></i></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><i class='bx bxl-instagram'></i></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><i class='bx bxl-youtube'></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="copy-right-area">
            <div class="copy-right-text">
                <p>
                    Copyright @
                    <script>document.write(new Date().getFullYear())</script>
                    Hilo. All Rights Reserved by
                    <a href="https://hibootstrap.com/" target="_blank">HiBootstrap</a>
                </p>
            </div>
        </div>
    </div>
</footer>

hilo_project/templates/_components/inner_banner.html
{% load static %}

<div class="inner-banner-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 col-md-4">
                <div class="inner-content">
                    <h2> {{ title }}</h2>
                    <ul>
                        <li><a href="{% url 'hilo:home' %}">Home</a></li>
                        <li> {{ page_name }}</li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-7 col-md-8">
                <div class="inner-img">
                    <img src="{{ page_icon }}" alt="Images" width="500px" height="300px">
                </div>
            </div>
        </div>
    </div>
</div>

hilo_project/templates/_components/messages.html
<!-- Modal -->
<div class="container-fluid">
{% if messages %}
    {% for message in messages %}
        <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        {% if message.tags == 'success' %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: green">
                                Muvafaqqiyatli!
                            </h5>
                        {% elif message.tags == 'warning' %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: orange">
                                Ogohlantirish!
                            </h5>
                        {% else %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: red">
                                Xatolik!
                            </h5>
                        {% endif %}
                    </div>
                    <div class="modal-body">
                        {{ message }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close">Close</button>
                        <a href="{% url 'hilo:home' %}" type="button" class="btn btn-primary">Bosh sahifa</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}
</div>

<!-- Script to trigger modal on page load -->
{% if messages %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endif %}

<script>
$(document).ready(function(){
    $('#messageModal').modal('show');

    // close tugmasi bosilganda modalni yopish
    $('#close').on('click', function() {
        $('#messageModal').modal('hide');
    });
});
</script>

hilo_project/templates/_components/preloader.html
{% load static %}

<div class="preloader">
    <div class="d-table">
        <div class="d-table-cell">
            <img src="{% static 'images/preloder-img.png' %}" alt="Images">
            <h2>Hilo</h2>
        </div>
    </div>
</div>

hilo_project/templates/_components/script.html
{% load static %}


<!-- Jquery Min JS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap Min JS -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- Owl Carousel Min JS -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- Nice Select Min JS -->
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<!-- Wow Min JS -->
<script src="{% static 'js/wow.min.js' %}"></script>
<!-- Meanmenu JS -->
<script src="{% static 'js/meanmenu.js' %}"></script>
<!-- Jquery Ui Min JS -->
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<!-- Ajaxchimp Min JS -->
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<!-- Form Validator Min JS -->
<script src="{% static 'js/form-validator.min.js' %}"></script>
<!-- Contact Form JS -->
<script src="{% static 'js/contact-form-script.js' %}"></script>
<!-- Mixitup Min JS -->
<script src="{% static 'js/mixitup.min.js' %}"></script>
<!-- Custom JS -->
<script src="{% static 'js/custom.js' %}"></script>

hilo_project/templates/_components/style.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!-- Animate Min CSS -->
<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
<!-- Flaticon CSS -->
<link rel="stylesheet" href="{% static 'fonts/flaticon.css' %}">
<!-- Boxicons CSS -->
<link rel="stylesheet" href="{% static 'css/boxicons.min.css' %}">
<!-- Owl Carousel Min CSS -->
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<!-- Nice Select Min CSS -->
<link rel="stylesheet" href="{% static 'css/nice-select.min.css' %}">
<!-- Meanmenu CSS -->
<link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
<!-- Style CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- Responsive CSS -->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<!-- Theme Dark CSS -->
<link rel="stylesheet" href="{% static 'css/theme-dark.css' %}">

hilo_project/templates/_components/top_header.html
{% load static %}

<header class="top-header top-header-bg">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4">
                <div class="top-header-social">
                    <ul>
                        <li>
                            <a href="#" target="_blank">
                                <i class='bx bxl-facebook'></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                <i class='bx bxl-twitter'></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                <i class='bx bxl-instagram'></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-9 col-md-8">
                <div class="top-header-right">
                    <div class="top-header-right-item">
                        <div class="language-list">
                            <select class="language-list-item">
                                <option>English</option>
                                <option>العربيّة</option>
                                <option>Deutsch</option>
                                <option>Português</option>
                                <option>简体中文</option>
                            </select>
                        </div>
                    </div>

                    <div class="top-header-right-item">
                        <ul class="top-header-list">
                            {% if request.user.is_authenticated %}
                                <li><a href="#">My Account({{ request.user.username }})</a></li>
                                <li><a href="{% url 'user:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'user:login' %}">Login</a></li>
                                <li><a href="{% url 'user:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

hilo_project/templates/base.html
<!doctype html>
{% load static %}
<html lang="zxx">
    <head>
        <!-- Required Meta Tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% include '_components/style.html' %}
        
        <!-- Favicon -->
        <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">

        <title>{{ title }}</title>
    </head>
    <body>
        <!-- Pre Loader -->
        {% include '_components/preloader.html' %}
        <!-- End Pre Loader -->

        <!-- Top Header Start -->
        {% include '_components/top_header.html' %}
        <!-- Top Header End -->

        <!-- Start Navbar Area -->
        {% include '_components/navbar.html' %}
        <!-- End Navbar Area -->

        <!-- Banner Area -->
        {% if request.path == '/' %}
            {% include '_components/banner.html' %}
        {% else %}
            {% include '_components/inner_banner.html' %}
        {% endif %} 
        <!-- Banner Area End -->

        {% block content %}
        	
        {% endblock %}

        <!-- Footer Area -->
        {% include '_components/footer.html' %}
        <!-- Footer Area End -->
        
        {% include '_components/messages.html' %}

        {% include '_components/script.html' %}       

    </body>
</html>

hilo_project/templates/components/blog.html
{% load static %}


<section class="blog-area pb-70">
    <div class="container">
        <div class="section-title text-center">
            <h2>Our Latest Blogs</h2>
            <p class="margin-auto">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget arcu luctus orci vulputate
                eleifend ut et odio. Proin purus mi, convallis sit amet pretium a, rhoncus aliquam purus.
            </p>
        </div>

        <div class="row pt-45">
            <div class="col-lg-4 col-md-6">
                <div class="blog-card">
                    <a href="blog-details.html">
                        <img src="{% static 'images/blog/blog-img1.jpg' %}" alt="Images">
                    </a>
                    <div class="content">
                        <span><i class='bx bx-time-five'></i> Nov 01, 2020</span>
                        <h3><a href="blog-details.html">We Always Ready to Give You Best Delivery Support </a></h3>
                        <p>
                            Lorem ipsum dolor sit amet, consetetur exit sadipscing elitr, sed diam.
                        </p>
                        <a href="#" class="read-btn">Read More</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6">
                <div class="blog-card">
                    <a href="blog-details.html">
                        <img src="{% static 'images/blog/blog-img2.jpg' %}" alt="Images">
                    </a>
                    <div class="content">
                        <span><i class='bx bx-time-five'></i> Nov 05, 2020</span>
                        <h3><a href="blog-details.html">Click and Make the Payment in the Most Easiest Way</a></h3>
                        <p>
                            Lorem ipsum dolor sit amet, consetetur exit sadipscing elitr, sed diam.
                        </p>
                        <a href="#" class="read-btn">Read More</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 offset-lg-0 offset-md-3">
                <div class="blog-card">
                    <a href="blog-details.html">
                        <img src="{% static 'images/blog/blog-img3.jpg' %}" alt="Images">
                    </a>
                    <div class="content">
                        <span><i class='bx bx-time-five'></i> Nov 07, 2020</span>
                        <h3><a href="blog-details.html">Global Ecommerce System Marked as a History </a></h3>
                        <p>
                            Lorem ipsum dolor sit amet, consetetur exit sadipscing elitr, sed diam.
                        </p>
                        <a href="#" class="read-btn">Read More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

hilo_project/templates/components/brand.html
{% load static %}


<div class="brand-area pb-100">
    <div class="container">
        <div class="brand-slider owl-carousel owl-theme">
            <div class="brand-item">
                <img src="{% static 'images/brand-logo/brand-img1.png' %}" alt="Images">
            </div>
            <div class="brand-item">
                <img src="{% static 'images/brand-logo/brand-img2.png' %}" alt="Images">
            </div>
            <div class="brand-item">
                <img src="{% static 'images/brand-logo/brand-img3.png' %}" alt="Images">
            </div>
            <div class="brand-item">
                <img src="{% static 'images/brand-logo/brand-img4.png' %}" alt="Images">
            </div>
            <div class="brand-item">
                <img src="{% static 'images/brand-logo/brand-img5.png' %}" alt="Images">
            </div>
            <div class="brand-item">
                <img src="{% static 'images/brand-logo/brand-img2.png' %}" alt="Images">
            </div>
        </div>
    </div>
</div>

hilo_project/templates/components/newsletter.html
{% load static %}

<div class="newsletter-area-section pt-100 pb-70">
    <div class="container">
        <div class="section-title text-center">
            <h2>Keep in Touch With Newsletter</h2>
            <p class="margin-auto">
                Get 35% Discount on Subscribe
            </p>
        </div>

        <div class="newsletter-area pt-45">
            <form class="newsletter-form" data-toggle="validator" method="POST">
                <input type="email" class="form-control" placeholder="Enter your email" name="EMAIL" required
                       autocomplete="off">
                <button class="subscribe-btn" type="submit">
                    Subscribe
                </button>
                <div id="validator-newsletter" class="form-result"></div>
            </form>
        </div>
    </div>
</div>